const D=window.NIHONGO_DATA;
const DAY=86400000;
const $=id=>document.getElementById(id);
const todayKey=()=>new Date().toISOString().slice(0,10);
const settings=JSON.parse(localStorage.getItem("nc_pwa_settings")||'{"goal":20,"newLimit":10,"autoAudio":false,"theme":"light"}');
let progress=JSON.parse(localStorage.getItem("nc_pwa_progress")||"{}");
let stats=JSON.parse(localStorage.getItem("nc_pwa_stats")||'{"reviews":0,"correct":0,"streak":0,"lastStudy":null,"days":{}}');
let custom=JSON.parse(localStorage.getItem("nc_pwa_custom")||"[]");
let lessonState=JSON.parse(localStorage.getItem("nc_pwa_lessons")||"{}");
let cards=[],queue=[],idx=0,current=null,revealed=false,libraryLevel="Alle",grammarLevel="N4",dojoSession=false,deferredPrompt=null,lastMainScreen="home";

function save(){localStorage.setItem("nc_pwa_settings",JSON.stringify(settings));localStorage.setItem("nc_pwa_progress",JSON.stringify(progress));localStorage.setItem("nc_pwa_stats",JSON.stringify(stats));localStorage.setItem("nc_pwa_custom",JSON.stringify(custom));localStorage.setItem("nc_pwa_lessons",JSON.stringify(lessonState));}
function refreshCards(){cards=[...D.buildCards(),...custom.map(c=>({...c,reading:c.reading||"",romaji:c.romaji||D.romajiFor(c.front)||"",exampleRomaji:c.exampleRomaji||D.romajiFor(c.example)||""}))];}
function pf(id){if(!progress[id])progress[id]={reps:0,due:0,interval:0,ease:2.4,mastered:false,again:0,hard:0,good:0,easy:0};return progress[id]}
function due(c){const p=pf(c.id);return p.reps>0&&p.due<=Date.now()}
function fresh(c){return pf(c.id).reps===0}
function eligible(c){if(c.level==="Eigene")return true;return ["N4","N3"].includes(c.level)&&["Vokabeln","Kanji","Grammatik"].includes(c.deck)}
function parts(c){const raw=String(c?.reading||"");const p=raw.split("·").map(x=>x.trim()).filter(Boolean);const kana=p.find(x=>/[ぁ-ゖァ-ヺ]/.test(x))||(/[ぁ-ゖァ-ヺ]/.test(String(c?.front||""))?String(c.front).replace(/[A-Za-z0-9～〜・＋+\/]/g,"").trim():"");const romaji=c?.romaji||p.find(x=>/[A-Za-zāīūēōĀĪŪĒŌ]/.test(x))||D.romajiFor(c?.front)||"";return{kana,romaji}}
function sentenceRomaji(c){return c?.exampleRomaji||D.romajiFor(c?.example)||""}
function weakScore(c){const p=pf(c.id);if(!p.reps)return 0;return(p.again||0)*4+(p.hard||0)*2-(p.easy||0)*.5+Math.max(0,3-p.interval)}
function weakest(){return cards.filter(c=>eligible(c)&&pf(c.id).reps>0).sort((a,b)=>weakScore(b)-weakScore(a))}
function toast(t){const el=$("toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1500)}
function updateStreak(){const t=todayKey();if(stats.lastStudy===t)return;if(stats.lastStudy){const d=(new Date(t+"T12:00:00")-new Date(stats.lastStudy+"T12:00:00"))/DAY;stats.streak=d===1?(stats.streak||0)+1:1}else stats.streak=1;stats.lastStudy=t}
function markStudy(){updateStreak();stats.days[todayKey()]=(stats.days[todayKey()]||0)+1;save()}
function applyTheme(){document.documentElement.dataset.theme=settings.theme||"light"}

function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");document.body.classList.toggle("learn-active",id==="learn");document.querySelectorAll(".nav-button").forEach(b=>b.classList.toggle("active",b.dataset.target===id));if(["home","library","learn","path","progress"].includes(id))lastMainScreen=id;window.scrollTo({top:0,left:0,behavior:"auto"});if(id==="library")renderLibrary();if(id==="path")renderPath();if(id==="progress")renderProgress();if(id==="settings")renderSettings();if(id==="learn"&&!current)buildQueue()}
document.querySelectorAll(".nav-button").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.target)));
document.querySelectorAll(".settings-trigger").forEach(b=>b.addEventListener("click",()=>showScreen($("settings").classList.contains("active")?lastMainScreen:"settings")));

const PATH=[["N5","Grundlage","Zum Nachschlagen vorhanden."],["N4","Aktiver Schwerpunkt","Wörter, Kanji und Grammatik für den nächsten Lernschritt."],["N3","Aufbau","Komplexere Wörter und Satzmuster."],["N2","Später","Fortgeschrittene Grammatik und formeller Wortschatz."],["N1","Später","Sehr fortgeschrittene Strukturen und Ausdrücke."]];
function levelStats(level){const set=cards.filter(c=>c.level===level&&["Vokabeln","Kanji","Grammatik"].includes(c.deck));const learned=set.filter(c=>pf(c.id).reps>0).length;return{total:set.length,learned,pct:set.length?Math.round(learned/set.length*100):0}}
function pathCards(target){$(target).innerHTML=PATH.map(([l,label,desc])=>{const s=levelStats(l);return`<div class="path-card"><div class="path-head"><div><strong>${l} · ${label}</strong><div class="muted">${desc}</div></div><span class="badge">${s.learned}/${s.total}</span></div><div class="progress" style="margin-top:9px"><i style="width:${s.pct}%"></i></div></div>`}).join("")}
function renderHome(){const pool=cards.filter(eligible),d=pool.filter(due).length,n=Math.min(pool.filter(fresh).length,settings.newLimit),l=pool.filter(c=>pf(c.id).reps>0).length,done=stats.days[todayKey()]||0,pct=Math.min(100,Math.round(done/settings.goal*100));$("due").textContent=d;$("fresh").textContent=n;$("streak").textContent=stats.streak||0;$("learned").textContent=l;$("goalText").textContent=`${done} / ${settings.goal} Karten`;$("daybar").style.width=pct+"%";$("heroTitle").textContent=pct>=100?"Tagesziel geschafft":d?`${d} Karten warten`:"Bereit für neue Karten?";$("heroText").textContent=pct>=100?"Für heute ist dein Ziel erreicht.":"Lernen fokussiert ganze Wörter, Kanji und Satzmuster aus N4 und N3.";pathCards("miniPath")}
$("startBtn").onclick=()=>{dojoSession=false;buildQueue();showScreen("learn")};

function buildQueue(){dojoSession=false;const pool=cards.filter(eligible),d=pool.filter(due).sort((a,b)=>weakScore(b)-weakScore(a)),n=pool.filter(fresh).slice(0,settings.newLimit);queue=[...d,...n].slice(0,settings.goal);if(!queue.length)queue=pool.slice().sort(()=>Math.random()-.5).slice(0,settings.goal);idx=0;showCard()}
function showCard(){current=queue[idx]||null;revealed=false;$("flashcard").classList.remove("flipped");$("answers").classList.remove("ready");if(!current){$("front").textContent="完了";$("frontKana").textContent="";$("frontRomaji").textContent="";$("meaning").textContent="Session beendet";$("example").textContent="";$("exampleRomaji").textContent="";$("exampleDe").textContent="";$("meta1").textContent="";$("meta2").textContent="";$("counter").textContent="";return}const r=parts(current);$("front").textContent=current.front;$("frontKana").textContent=r.kana;$("frontRomaji").textContent=r.romaji;$("meaning").textContent=current.meaning||"";$("example").textContent=current.example||"";$("exampleRomaji").textContent=sentenceRomaji(current);$("exampleDe").textContent=current.exampleDe||"";const meta=`${current.level||""} · ${current.deck}`;$("meta1").textContent=meta;$("meta2").textContent=meta;$("counter").textContent=`${idx+1} / ${queue.length}${dojoSession?" · Dojo":""}`;if(settings.autoAudio)setTimeout(()=>speak(current.front),140)}
function flip(){if(!current)return;$("flashcard").classList.toggle("flipped");if(!revealed){revealed=true;$("answers").classList.add("ready")}}
$("flashcard").onclick=flip;$("flashcard").onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();flip()}};
$("speak").onclick=e=>{e.stopPropagation();if(current)speak(current.front)};
function speak(text){if(!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.82;speechSynthesis.speak(u)}
document.querySelectorAll(".rating").forEach(btn=>btn.onclick=()=>{if(!current||!revealed)return;const g=btn.dataset.g,p=pf(current.id);stats.reviews++;p.reps++;p[g]=(p[g]||0)+1;if(g!=="again")stats.correct++;if(g==="again"){p.interval=0;p.due=Date.now()+60000;p.ease=Math.max(1.3,p.ease-.2);p.mastered=false}if(g==="hard"){p.interval=Math.max(1,p.interval?Math.round(p.interval*1.35):1);p.due=Date.now()+p.interval*DAY;p.ease=Math.max(1.3,p.ease-.15)}if(g==="good"){p.interval=p.interval?Math.max(2,Math.round(p.interval*p.ease)):1;p.due=Date.now()+p.interval*DAY;p.mastered=p.interval>=14}if(g==="easy"){p.ease+=.15;p.interval=p.interval?Math.max(4,Math.round(p.interval*p.ease*1.35)):4;p.due=Date.now()+p.interval*DAY;p.mastered=p.interval>=14}markStudy();idx++;showCard();renderHome();renderProgress()});

function renderLevelButtons(){const levels=["Alle","N5","N4","N3","N2","N1"];$("libraryLevels").innerHTML=levels.map(l=>`<button class="level-button ${l===libraryLevel?"active":""}" data-l="${l}">${l}</button>`).join("");$("libraryLevels").querySelectorAll("button").forEach(b=>b.onclick=()=>{libraryLevel=b.dataset.l;renderLevelButtons();renderLibrary()})}
function renderLibrary(){const type=$("filter").value,q=$("search").value.trim().toLowerCase();const list=cards.filter(c=>["Vokabeln","Kanji","Grammatik","Eigene Karten"].includes(c.deck)&&(type==="all"||c.deck===type)&&(libraryLevel==="Alle"||c.level===libraryLevel)&&(!q||`${c.front} ${c.reading} ${c.romaji} ${c.meaning} ${c.example} ${c.exampleDe}`.toLowerCase().includes(q)));$("libraryCount").textContent=`${list.length} Karten`;$("libraryList").innerHTML=list.slice(0,220).map(c=>{const r=parts(c),sr=sentenceRomaji(c);return`<article class="library-card"><div class="library-head"><div><div class="library-jp">${c.front}</div>${r.kana?`<div class="library-kana">${r.kana}</div>`:""}${r.romaji?`<div class="romaji">${r.romaji}</div>`:""}</div><span class="badge">${c.level||""} · ${c.deck}</span></div><div class="library-meaning">${c.meaning||""}</div>${c.example?`<div class="library-example"><div>${c.example}</div>${sr?`<div class="romaji">${sr}</div>`:""}${c.exampleDe?`<div class="de">${c.exampleDe}</div>`:""}</div>`:""}</article>`}).join("")||'<div class="panel muted">Keine Karten für diese Filterung.</div>';const weak=weakest();$("dojoText").textContent=weak.length?`${weak.length} unsichere Karten sind bereit.`:"Dojo wird nach deinen ersten Bewertungen automatisch gefüllt."}
$("filter").onchange=renderLibrary;$("search").oninput=renderLibrary;$("dojoBtn").onclick=()=>{const weak=weakest();if(!weak.length){toast("Noch keine bewerteten Schwächen vorhanden");return}dojoSession=true;queue=weak.slice(0,Math.max(10,settings.goal));idx=0;showCard();showScreen("learn")};$("addBtn").onclick=()=>showScreen("addCard");

function renderGrammarTabs(){const levels=["N4","N3"];$("grammarLevels").innerHTML=levels.map(l=>`<button class="grammar-level ${l===grammarLevel?"active":""}" data-l="${l}">${l}</button>`).join("");$("grammarLevels").querySelectorAll("button").forEach(b=>b.onclick=()=>{grammarLevel=b.dataset.l;$("lessonDetail").innerHTML="";renderGrammarTabs();renderLessonOverview()})}
function lessons(){return D.LESSONS.filter(l=>l.level===grammarLevel)}function lessonDone(id){return!!lessonState[id]}
function renderPath(){pathCards("fullPath");renderGrammarTabs();renderLessonOverview()}
function renderLessonOverview(){const list=lessons();if(!list.length){$("lessonOverview").innerHTML=`<div class="panel muted">Für ${grammarLevel} sind noch keine geführten Lektionen hinterlegt.</div>`;$("lessonDetail").innerHTML="";return}const done=list.filter(l=>lessonDone(l.id)).length;let next=list.findIndex(l=>!lessonDone(l.id));if(next<0)next=0;const item=list[next];$("lessonOverview").innerHTML=`<div class="lesson-card"><div class="top"><strong>${grammarLevel}</strong><span class="badge">${done}/${list.length}</span></div><div class="progress" style="margin-top:8px"><i style="width:${Math.round(done/list.length*100)}%"></i></div><div class="title">${done===list.length?"Lektionen wiederholen":item.title}</div><div class="muted">${done===list.length?"Alle vorhandenen Lektionen sind abgeschlossen.":item.summary}</div><button class="primary-button full" id="continueLesson" style="margin-top:10px">${done===list.length?"Erste Lektion öffnen":"Lektion beginnen"}</button></div><details class="lesson-list"><summary>Alle Lektionen anzeigen</summary>${list.map((l,i)=>`<button class="${lessonDone(l.id)?"done":""}" data-i="${i}"><strong>${lessonDone(l.id)?"✓ ":`${i+1}. `}${l.title}</strong><div class="muted">${l.summary}</div></button>`).join("")}</details>`;$("continueLesson").onclick=()=>showLesson(next);$("lessonOverview").querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>showLesson(+b.dataset.i))}
function showLesson(i){const list=lessons(),l=list[i];if(!l)return;const grammar=D.GRAMMAR.find(g=>g[0]===l.level&&(g[1]===l.title||String(g[1]).includes(String(l.title).replace(/[～〜]/g,""))));const pattern=grammar?grammar[2]:D.romajiFor(String(l.title).replace(/[～〜]/g,""));$("lessonDetail").innerHTML=`<div class="lesson-detail"><div class="muted">Lektion ${i+1} von ${list.length} · ${l.level}${lessonDone(l.id)?" · abgeschlossen":""}</div><div class="lesson-detail-title">${l.title}</div>${pattern?`<div class="romaji">${pattern}</div>`:""}<div class="lesson-step"><strong>Bedeutung</strong><p>${l.summary}</p></div><div class="lesson-step"><strong>So funktioniert es</strong><p>${l.explanation}</p></div><div class="lesson-step"><strong>Beispiele</strong>${l.examples.map(e=>`<div class="lesson-example"><div class="jp">${e[0]}</div>${D.romajiFor(e[0])?`<div class="romaji">${D.romajiFor(e[0])}</div>`:""}<div class="muted">${e[1]}</div></div>`).join("")}</div><div class="lesson-step"><strong>Merke</strong><p>${l.tip}</p></div><div class="lesson-nav"><button class="outline-button" id="lessonPrev" ${i===0?"disabled":""}>Zurück</button><button class="primary-button" id="lessonNext">${i===list.length-1?"Abschließen":"Verstanden & weiter"}</button></div></div>`;$("lessonPrev").onclick=()=>{if(i>0)showLesson(i-1)};$("lessonNext").onclick=()=>{lessonState[l.id]=true;save();if(i<list.length-1)showLesson(i+1);else{$("lessonDetail").innerHTML="";renderLessonOverview();toast("Lektion abgeschlossen")}}}

$("verbsBtn").onclick=()=>{$("toolContent").innerHTML=D.VERBS.map(v=>`<div class="tool-result"><strong>${v.dict}</strong>${D.romajiFor(v.dict)?`<div class="romaji">${D.romajiFor(v.dict)}</div>`:""}<div class="muted">${v.meaning}</div>${[["ます",v.masu],["Negativ",v.negative],["Vergangenheit",v.past],["て-Form",v.te],["Potential",v.potential]].map(([l,j])=>`<div class="form-line"><strong>${l}</strong><div>${j}</div>${D.romajiFor(j)?`<div class="romaji">${D.romajiFor(j)}</div>`:""}</div>`).join("")}</div>`).join("")};
$("numbersBtn").onclick=()=>{const rows=[["1–10","一 いち · 二 に · 三 さん · 四 よん · 五 ご · 六 ろく · 七 なな · 八 はち · 九 きゅう · 十 じゅう"],["100–10.000","百 ひゃく · 千 せん · 一万 いちまん"],["Uhrzeit","一時 いちじ · 四時 よじ · 七時 しちじ · 九時 くじ"],["Minuten","一分 いっぷん · 三分 さんぷん · 六分 ろっぷん · 十分 じゅっぷん"]];$("toolContent").innerHTML=rows.map(r=>`<div class="tool-result"><strong>${r[0]}</strong><div>${r[1]}</div>${D.romajiFor(r[1])?`<div class="romaji">${D.romajiFor(r[1])}</div>`:""}</div>`).join("")};
$("countersBtn").onclick=()=>{$("toolContent").innerHTML=D.COUNTERS.map(x=>`<div class="tool-result"><strong>${x[0]}</strong><div class="muted">${x[2]}</div><div style="margin-top:5px">${x[3]}</div>${D.romajiFor(x[3])?`<div class="romaji">${D.romajiFor(x[3])}</div>`:""}</div>`).join("")};

function renderProgress(){$("reviews").textContent=stats.reviews||0;$("accuracy").textContent=stats.reviews?Math.round((stats.correct||0)/stats.reviews*100)+"%":"–";$("mastered").textContent=Object.values(progress).filter(p=>p.mastered).length;$("pstreak").textContent=stats.streak||0;$("levelProgress").innerHTML=["N5","N4","N3","N2","N1"].map(l=>{const s=levelStats(l);return`<div style="margin:10px 0"><div style="display:flex;justify-content:space-between"><strong>${l}</strong><span class="muted">${s.learned}/${s.total}</span></div><div class="progress" style="margin-top:5px"><i style="width:${s.pct}%"></i></div></div>`}).join("")}
function renderSettings(){$("goal").value=settings.goal||20;$("newLimit").value=settings.newLimit||10;$("audioToggle").classList.toggle("on",!!settings.autoAudio);$("themeLight").classList.toggle("active",(settings.theme||"light")==="light");$("themeDark").classList.toggle("active",settings.theme==="dark")}
$("goal").onchange=e=>{settings.goal=+e.target.value;save();renderHome()};$("newLimit").onchange=e=>{settings.newLimit=+e.target.value;save();renderHome()};$("audioToggle").onclick=()=>{settings.autoAudio=!settings.autoAudio;save();renderSettings()};$("themeLight").onclick=()=>{settings.theme="light";applyTheme();save();renderSettings()};$("themeDark").onclick=()=>{settings.theme="dark";applyTheme();save();renderSettings()};$("reset").onclick=()=>{if(confirm("Lernfortschritt wirklich zurücksetzen? Eigene Karten bleiben erhalten.")){progress={};stats={reviews:0,correct:0,streak:0,lastStudy:null,days:{}};lessonState={};save();renderHome();renderProgress();renderPath();toast("Zurückgesetzt")}};
$("saveCard").onclick=()=>{const front=$("newFront").value.trim(),kana=$("newReading").value.trim(),meaning=$("newMeaning").value.trim(),romaji=$("newRomaji").value.trim(),example=$("newExample").value.trim(),exampleRomaji=$("newExampleRomaji").value.trim();if(!front||!kana||!meaning||!romaji){toast("Japanisch, Kana, Romaji und Bedeutung fehlen");return}if(example&&!exampleRomaji){toast("Zum Beispielsatz fehlt Romaji");return}custom.push({id:"custom-"+Date.now(),deck:$("newDeck").value,level:$("newLevel").value,front,reading:kana,romaji,meaning,example,exampleRomaji,exampleDe:""});save();refreshCards();["newFront","newReading","newRomaji","newMeaning","newExample","newExampleRomaji"].forEach(id=>$(id).value="");toast("Karte gespeichert");showScreen("library")};$("cancelCard").onclick=()=>showScreen("library");
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({version:19,exportedAt:new Date().toISOString(),settings,progress,stats,custom,lessonState},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="rethink-nihongo-backup.json";a.click();URL.revokeObjectURL(a.href)};$("importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const d=JSON.parse(await file.text());if(d.settings)Object.assign(settings,d.settings);if(d.progress)progress=d.progress;if(d.stats)stats=d.stats;if(Array.isArray(d.custom))custom=d.custom;if(d.lessonState)lessonState=d.lessonState;save();refreshCards();applyTheme();renderHome();renderLibrary();renderProgress();renderSettings();toast("Lernstand importiert")}catch{toast("Import konnte nicht gelesen werden")}};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.add("show")});$("installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").classList.remove("show")};
refreshCards();applyTheme();renderLevelButtons();renderHome();renderLibrary();renderProgress();renderSettings();buildQueue();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));
